<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php if (!$block->isContentMode() || $block->isMixedMode()) :?>
<!--<?//= $block->getProductListHtml() ?>   -->
    <div class="sections-container">
        <h3>Laptops</h3>
        <div class="section-first">
            <div class="section-first-column">
                <a href="#" class="section-first-column-item">
                    <img src="<?=$block->getViewFileUrl('images/windows-tablet.png')?>" alt="man" class="section-first-column-item-img">
                    <div class="section-first-column-item-title">Windows laptops</div>
                    <div class="section-first-column-item-subtitle">With the well-known Windows, you can use almost every application.</div>
                </a>
                <a href="#" class="section-first-column-item">
                    <img src="<?=$block->getViewFileUrl('images/apple-tablet.png')?>" alt="man" class="section-first-column-item-img">
                    <div class="section-first-column-item-title">Apple MacBook</div>
                    <div class="section-first-column-item-subtitle">Use macOS and work together with other Apple devices.</div>
                </a>
                <a href="#" class="section-first-column-item">
                    <img src="<?=$block->getViewFileUrl('images/chrome-tablet.png')?>" alt="man" class="section-first-column-item-img">
                    <div class="section-first-column-item-title">Back to School laptops</div>
                    <div class="section-first-column-item-subtitle">View all our promotions for student laptops here.</div>
                </a>
                <a  href="#" class="section-first-column-item">
                    <img src="<?=$block->getViewFileUrl('images/business-tablet.png')?>" alt="man" class="section-first-column-item-img">
                    <div class="section-first-column-item-title">Business laptops</div>
                    <div class="section-first-column-item-subtitle">Windows Pro is safe and suitable for working remotely.</div>
                </a>
            </div>
            <div class="section-first-column">
                <div class="section-first-column-banner">
                    <img src="<?=$block->getViewFileUrl('images/banner-laptop.png')?>" alt="man" class="section-first-column-banner-img">
                    <button class="section-first-column-banner-btn"><span>LAPTOPS</span><br><span>Open and shut case</span> </button>
                </div>
            </div>
        </div>
        <div class="section-divider">
            <div class="section-divider-line"></div>
            <ul class="section-divider-list">
                <li  class="section-divider-list-item">
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">Ordered before <span>23:59</span>, delivered tomorrow <span>for free</span></a>
                </li>
                <li>
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">14 stores</a>
                </li>
                <li>
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">Our app</a>
                </li>
                <li>
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#"><span>Best</span> webshop 2021</a>
                </li>
            </ul>
            <div class="section-divider-line"></div>
        </div>
        <div class="section-brands">
           <a href="#" class="section-brands-item">
               <img src="<?=$block->getViewFileUrl('images/hp.png')?>" alt="hp">
           </a>
           <a href="#" class="section-brands-item">
               <img src="<?=$block->getViewFileUrl('images/lenovo.png')?>" alt="lenovo">
           </a>
           <a href="#" class="section-brands-item">
               <img src="<?=$block->getViewFileUrl('images/acer.png')?>" alt="acer">
           </a>
           <a href="#" class="section-brands-item">
               <img src="<?=$block->getViewFileUrl('images/asus.png')?>" alt="asus">
           </a>
           <a href="#" class="section-brands-item">
               <img src="<?=$block->getViewFileUrl('images/samsung.png')?>" alt="samsung">
           </a>
           <a href="#" class="section-brands-item">
               <img src="<?=$block->getViewFileUrl('images/msi.png')?>" alt="msi">
           </a>
        </div>
        <h4>Back to school laptops</h4>
        <div class="section-second">
            <a href="#" class="section-second-item">
                <img src="<?=$block->getViewFileUrl('images/backtoschool.png')?>" alt="man" class="section-first-column-item-img">
                <div class="section-second-item-title">All Back to School laptops</div>
                <div class="section-second-item-subtitle">View all student laptops from our assortment here.</div>
            </a>
            <a href="#" class="section-second-item">
                <img src="<?=$block->getViewFileUrl('images/social.png')?>" alt="man" class="section-first-column-item-img">
                <div class="section-second-item-title">Laptops for social, cultural, and economics studies</div>
                <div class="section-second-item-subtitle">These laptops are ideal for working on reports and presentations.</div>
            </a>
            <a href="#" class="section-second-item">
                <img src="<?=$block->getViewFileUrl('images/creative.png')?>" alt="man" class="section-first-column-item-img">
                <div class="section-second-item-title">Laptops for creative studies</div>
                <div class="section-second-item-subtitle">These fast laptops are ideal for photo and video editing.</div>
            </a>
            <a href="#" class="section-second-item">
                <img src="<?=$block->getViewFileUrl('images/technical.png')?>" alt="man" class="section-first-column-item-img">
                <div class="section-second-item-title">Laptops for technical studies</div>
                <div class="section-second-item-subtitle">Create 3D designs on these laptops with powerful video cards.</div>
            </a>
        </div>
        <h4>Laptops</h4>
        <div class="section-third">

            <a href="#" class="section-third-bigcontainer">
                <img src="<?=$block->getViewFileUrl('images/employers.png')?>" alt="employers">
            </a>
            <a href="#" class="section-third-smallcontainer">
                <img class="section-third-smallcontainer-img" src="<?=$block->getViewFileUrl('images/notebooks.png')?>" alt="laptop">
                <div class="section-third-smallcontainer-title">All laptops</div>
                <div class="section-third-smallcontainer-subtitle">Want to buy a new laptop? View our large assortment of laptops and find the laptop that suits your use.</div>
            </a>
            <div  class="section-third-smallcontainer">
                <div class="section-third-smallcontainer-section">
                    <h3 class="section-third-smallcontainer-header">Help choosing</h3>
                    <div class="section-third-smallcontainer-subtitle">Answer some questions and find the best one for you.</div>
                </div>
                <img class="section-third-smallcontainer-img_employer" src="<?=$block->getViewFileUrl('images/woman-employer.png')?>" alt="employer">
                <button class="section-third-smallcontainer-btn">Start the product filter</button>
            </div>
        </div>
        <h4>Quickly navigate to</h4>
        <div class="section-navigate">
            <a class="section-navigate-item">Coolblue's Choice laptops</a>
            <a class="section-navigate-item">Windows 10 student laptops</a>
            <a class="section-navigate-item">Gaming laptops</a>
            <a class="section-navigate-item">2-in-1 laptops</a>
            <a class="section-navigate-item">Windows laptops with Microsoft Office</a>
            <a class="section-navigate-item">Laptops for photo editing</a>
        </div>
        <div class="section-divider">
            <div class="section-divider-line"></div>
            <ul class="section-divider-list">
                <li  class="section-divider-list-item">
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">Ordered before <span>23:59</span>, delivered tomorrow <span>for free</span></a>
                </li>
                <li>
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">14 stores</a>
                </li>
                <li>
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">Our app</a>
                </li>
                <li>
                    <svg aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#"><span>Best</span> webshop 2021</a>
                </li>
            </ul>
            <div class="section-divider-line"></div>
        </div>
        <h4>Inspiration</h4>
        <?php
        echo $this->getLayout()
            ->createBlock('Magento\Cms\Block\Block')
            ->setBlockId('laptop-slider')
            ->toHtml();
        ?>
        <h4>Advice</h4>
        <div class="section-advice">
            <div class="section-advice-column">
                <img src="<?=$block->getViewFileUrl('images/laptop-choice.png')?>" alt="laptop-choice">
                <div class="section-advice-column-title">Which laptop suits you?</div>
                <div class="section-advice-column-text">Everybody uses a laptop once in a while. There are many different types of laptops. We divide them into 3 types, Windows laptops, Apple MacBook, and Google Chromebook. They differ in appearance and name, but also in operating system. Which laptop you need depends on both preference and use. There are students who use it at school, employees who use a laptop for business, and families who need a laptop for home use. Aren't you sure yet which laptop you want to buy? Get advice from our laptop expert and be inspired.</div>
                <a class="section-advice-column-link" href="#"><span>></span> Read the advice on which laptop is suitable for you here</a>
            </div>
            <div class="section-advice-column">
                <img src="<?=$block->getViewFileUrl('images/laptop-size.png')?>" alt="laptop-size">
                <div class="section-advice-column-title">Which laptop size suits you?</div>
                <div class="section-advice-column-text">The size of a laptop depends on the use. If you use it on the go for work or school, it's useful that the laptop is up to 14 inches and compact and doesn't weigh more than 1.5kg. That way, you can easily take the laptop with you in your laptop bag or backpack. A larger size laptop is mainly useful when you game a lot or edit photos or videos. So, think of what you want to use the laptop for beforehand. Do you want more information? We're happy to help you with some examples.</div>
                <a class="section-advice-column-link" href="#"><span>></span> Read the advice on choosing an inch-size here</a>
            </div>
            <div class="section-advice-column">
                <img src="<?=$block->getViewFileUrl('images/win11.png')?>" alt="laptop-size">
                <div class="section-advice-column-title">What's Windows 11?</div>
                <div class="section-advice-column-text">Windows 11 is the latest operating system by Microsoft. More and more new laptops have this new version by default. Windows 11 looks modern and calm at the same time, thanks to the transparent windows. Even though there are innovations, this version doesn't feel different. You don't have to worry about getting used to it when you switch. If you currently have a laptop with Windows 10, there's a great chance that you can upgrade it to Windows 11 for free. We're happy to explain to you how you know the upgrade is ready for you.</div>
                <a class="section-advice-column-link" href="#"><span>></span> Read everything on Windows 11 here</a>
            </div>
        </div>
        <h4>Laptops for every usage situation</h4>
        <div class="section-forth">
            <div class="section-forth-list">
                <a href="#" class="section-forth-list-item">
                    <img src="<?=$block->getViewFileUrl('images/studies-laptop.png')?>" alt="studies-laptop.png">
                    <div>Laptops for school and studies</div>
                </a>
                <a href="#" class="section-forth-list-item">
                    <img src="<?=$block->getViewFileUrl('images/gaming-laptop.png')?>" alt="gaming-laptop.png">
                    <div>Gaming laptops</div>
                </a>
                <a href="#" class="section-forth-list-item">
                    <img src="<?=$block->getViewFileUrl('images/editing-laptop.png')?>" alt="editing-laptop.png">
                    <div>Laptops for photo editing</div>
                </a>
                <a href="#" class="section-forth-list-item">
                    <img src="<?=$block->getViewFileUrl('images/video-editing-laptop.png')?>" alt="video-editing-laptop.png">
                    <div>Laptops for video editing</div>
                </a>
                <a href="#" class="section-forth-list-item">
                    <img src="<?=$block->getViewFileUrl('images/laptop-on-go.png')?>" alt="laptop-on-go.png">
                    <div>Laptops for on the go</div>
                </a>
            </div>
        </div>
        <h4>Laptops in the store</h4>
        <div class="section-advice">
            <div class="section-advice-column">
                <img src="<?=$block->getViewFileUrl('images/store-near-you.png')?>" alt="store-near-you.png">
                <div class="section-advice-column-title">Find a store near you?</div>
                <div class="section-advice-column-text">You can choose a laptop based on the hardware specifications. But it's also nice to know how sturdy the hinges are or how heavy that 17-inch laptop actually is. There's always a large stock of laptops in our stores.</div>
                <button class="section-advice-column-btn">Visit one of our stores</button>
            </div>
            <div class="section-advice-column">
                <img src="<?=$block->getViewFileUrl('images/advice-by.png')?>" alt="advice-by.png">
                <div class="section-advice-column-title">Advice by appointment</div>
                <div class="section-advice-column-text">Do you want 8GB RAM? Or do you need 32GB? Do you keep everything in the cloud or do you need internal storage? And what's the difference between M1 and M2? Make an appointment with one of our experts in our stores and they'll answer all your questions.</div>
                <button class="section-advice-column-btn">Make an appointment</button>
            </div>
            <div class="section-advice-column">
                <img src="<?=$block->getViewFileUrl('images/what-can-you-find.png')?>" alt="what-can-you-find.png">
                <div class="section-advice-column-title">Which laptops can you find in our stores?</div>
                <div class="section-advice-column-text">There are many laptops to view in our stores. Do you want to know if the laptop of your choice is available in our store in your area? View the page below and select the desired location. The coffee is already waiting for you.</div>
                <button class="section-advice-column-btn">View these laptops in the store</button>
            </div>
        </div>
        <div class="section-shortlinks">
            <ul class="section-shortlinks_lists">
                <li class="section-shortlinks_item">
                    <h3 class="section-shortlinks_item_title">A</h3>
                    <ul class="section-shortlinks_item_list">
                        <li><a class="section-shortlinks_item_link" href="">Acer laptops</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Apple MacBook</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Asus laptops</a></li>
                    </ul>
                </li>
                <li class="section-shortlinks_item">
                    <h3 class="section-shortlinks_item_title">B</h3>
                    <ul class="section-shortlinks_item_list">
                        <li><a class="section-shortlinks_item_link" href="">Back to School laptops</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Best laptops according to our customers</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Black Friday laptop deals</a></li>
                    </ul>
                </li>
                <li class="section-shortlinks_item">
                    <h3 class="section-shortlinks_item_title">C</h3>
                    <ul class="section-shortlinks_item_list">
                        <li><a class="section-shortlinks_item_link" href="">Cheap laptops</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Christmas laptop deals</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Chromebooks</a></li>
                    </ul>
                </li>
                <li class="section-shortlinks_item">
                    <h3 class="section-shortlinks_item_title">D</h3>
                    <ul class="section-shortlinks_item_list">
                        <li><a class="section-shortlinks_item_link" href="">Dell laptops</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Dynabook laptops</a></li>
                        <li><a class="section-shortlinks_item_link" href="">Dynabook laptops</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
<?php endif; ?>
