<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright">
    <div class="footer-copyright-section">
        <ul>
            <li><a href="">Terms & Conditions</a></li>
            <li><a href="">Privacy</a></li>
            <li><a href="">Cookies</a></li>
            <li><a href="">Nederlands (NL)</a></li>
        </ul>
        <span>© 1999 - 2022 - Coolblue B.V.</span>
        <span>Rating by costumers: Kiyoh 9 / 10 - <a href="#">12,285 reviews</a> </span>
    </div>
</small>
