<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="footer-container">
    <div class="footer">
<!--        <div>-->
<!--            <p>You previously viewed:</p>-->
<!--            <div>-->
<!--                <p>View your products anywhere</p>-->
<!--                <p>Log in to see products you previously viewed.</p>-->
<!--                <button>Log in</button>-->
<!--                <p>Don't have an account yet?</p><a href="#">Start here</a>-->
<!--            </div>-->
<!--            <a href="#">View your personal recommendations</a>-->
<!--        </div>-->
        <div class="footer-checklist-container">
            <div class="footer-checklist">
                <div class="footer-smile-container">
                <p>anything for a smile
                </p>
                <span class="footer-checklist-smileicon">
                    <svg class="icon icon--size-2 icon--color-blue" aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M42 24c0 9.941-8.059 18-18 18S6 33.941 6 24 14.059 6 24 6s18 8.059 18 18Zm6 0c0 13.255-10.745 24-24 24S0 37.255 0 24 10.745 0 24 0s24 10.745 24 24Zm-33.377 2.543a3 3 0 0 0-5.245 2.914c3.017 5.43 7.677 7.81 12.189 8.277 4.337.449 8.599-.858 11.233-2.834a3 3 0 1 0-3.6-4.8c-1.365 1.024-4.103 1.967-7.016 1.666-2.738-.283-5.578-1.653-7.561-5.223ZM17 13a3 3 0 0 1 3 3v4a3 3 0 1 1-6 0v-4a3 3 0 0 1 3-3Zm18 3a3 3 0 1 0-6 0v4a3 3 0 1 0 6 0v-4Z"></path>
                    </svg>
                </span>
                </div>
            <ul>
                <li>
                    <svg class="icon icon--color-green" aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">Ordered before <span>23:59</span>, delivered tomorrow <span>for free</span></a>
                </li>
                <li>
                    <svg class="icon icon--color-green" aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">14 stores</a>
                </li>
                <li>
                    <svg class="icon icon--color-green" aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#">Our app</a>
                </li>
                <li>
                    <svg class="icon icon--color-green" aria-hidden="true" viewBox="0 0 48 48" focusable="false">
                        <path d="M39.39 9.54a5 5 0 1 1 7.22 6.92L23.622 40.447A4.984 4.984 0 0 1 20.052 42a4.984 4.984 0 0 1-3.6-1.477L1.464 25.535a5 5 0 1 1 7.072-7.07l11.388 11.388L39.39 9.54Z"></path>
                    </svg>
                    <a href="#"><span>Best</span> webshop 2021</a>
                </li>
            </ul>
        </div>
        </div>
        <div class="footer-feedback-container">
            <div class="footer-feedback">
                <div class="footer-feedback-image">
                    <img src="<?=$block->getViewFileUrl('images/customer-service-employee.png')?>" alt="man" class="section3__img">
                </div>
                <div class="footer-feedback-question">
                    <p class="footer-feedback-question-title">Do you have a question?</p>
                    <p class="footer-feedback-question-text">Find your answer quickly and easily on our customer service page.</p>
                    <ul class="footer-feedback-question-list">
                        <li class="footer-feedback-question-item">
                            <a class="footer-feedback-question-link" href="">
                                <svg class="footer-feedback-question-link-icon" width="40px" height="40px">
                                    <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-facebook')?>"></use>
                                </svg>
                                Facebook
                            </a>
                        </li>
                        <li class="footer-feedback-question-item">
                            <a class="footer-feedback-question-link" href="">
                                <svg class="footer-feedback-question-link-icon" width="40px" height="40px">
                                    <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-youtube')?>"></use>
                                </svg>
                                YouTube
                            </a>
                        </li>
                        <li class="footer-feedback-question-item">
                            <a class="footer-feedback-question-link" href="">
                                <svg class="footer-feedback-question-link-icon" width="40px" height="40px">
                                    <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-twitter')?>"></use>
                                </svg>
                                Twitter
                            </a>
                        </li>
                        <li class="footer-feedback-question-item">
                            <a class="footer-feedback-question-link" href="">
                                <svg class="footer-feedback-question-link-icon" width="40px" height="40px">
                                    <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-store')?>"></use>
                                </svg>
                                14 stores
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="footer-feedback-newsletter">
                    <p class="footer-feedback-newsletter-title">Sign up for our newsletter</p>
                    <p class="footer-feedback-newsletter-text">Receive the best promotions and personal advice.</p>
                    <form class="footer-feedback-newsletter-form" action="submit">
                        <label for="footer-input" class="footer-feedback-newsletter-form-label">Email address</label>
                        <input name="footer-input" type="email" class="footer-feedback-newsletter-form-input"/>
                        <button class="footer-feedback-newsletter-form-button">Sing up</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="footer-links-container">
            <div class="footer-links">
                <ul class="footer-links-list">
                    <li class="footer-links-item">
                        <ul class="footer-links-item-list">
                            <li class="footer-links-item-list-link"><a href="">Customer Service</a></li>
                            <li><a href="">Delivery and installation</a></li>
                            <li><a href="">Payment</a></li>
                            <li><a href="">Exchange and return</a></li>
                            <li><a href="">Warranty and repairs</a></li>
                            <li><a href="">Order</a></li>
                            <li><a href="">Stores</a></li>
                            <li><a href="">Status of my order</a></li>
                            <li><a href="">Register a return or repair</a></li>
                            <li><a href="">All orders</a></li>
                            <li><a href="">Log in</a></li>
                            <li class="footer-links-item-list-link-last"><a href="">> To the customer service</a></li>
                        </ul>
                    </li>
                    <li class="footer-links-item">
                        <ul class="footer-links-item-list">
                            <li class="footer-links-item-list-link"><a href="">Business</a></li>
                            <li><a href="">Business order</a></li>
                            <li><a href="">Business gift cards</a></li>
                            <li><a href="">Christmas gifts</a></li>
                            <li><a href="">Company Stores</a></li>
                            <li><a href="">Home Office Store</a></li>
                            <li><a href="">Bring Your Own Device</a></li>
                            <li><a href="">Gift Store</a></li>
                            <li><a href="">Affiliate program</a></li>
                            <li class="footer-links-item-list-link-last"><a href="">> Everything on B2B</a></li>
                        </ul>
                    </li>
                    <li class="footer-links-item">
                        <ul class="footer-links-item-list">
                            <li class="footer-links-item-list-link"><a href="">Our stores</a></li>
                            <li><a href="">Almere</a></li>
                            <li><a href="">Amsterdam</a></li>
                            <li><a href="">Arnhem</a></li>
                            <li><a href="">Den Bosch</a></li>
                            <li><a href="">The Hague</a></li>
                            <li><a href="">Eindhoven</a></li>
                            <li><a href="">Groningen</a></li>
                            <li><a href="">Haarlem</a></li>
                            <li><a href="">Leiden</a></li>
                            <li><a href="">Nijmegen</a></li>
                            <li><a href="">Rotterdam</a></li>
                            <li><a href="">Rotterdam Alexandrium</a></li>
                            <li><a href="">Tilburg</a></li>
                            <li><a href="">Utrecht</a></li>
                            <li class="footer-links-item-list-link-last"><a href="">> Everything on our shops</a></li>
                        </ul>
                    </li>
                    <li class="footer-links-item">
                        <ul class="footer-links-item-list">
                            <li class="footer-links-item-list-link"><a href="">About Coolblue</a></li>
                            <li><a href="">Our assortment</a></li>
                            <li><a href="">Company website</a></li>
                            <li><a href="">Gift cards</a></li>
                            <li><a href="">Careers at Coolblue</a></li>
                            <li><a href="">Development jobs</a></li>
                            <li><a href="">The Coolblue App</a></li>
                            <li><a href="">Coolblue Belgium</a></li>
                            <li><a href="">Coolblue Germany</a></li>
                            <li><a href="">Privacy</a></li>
                            <li class="footer-links-item-list-link-last"><a href="">> Everything on Coolblue</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <div class="footer-social-container">
            <div class="footer-social">
                <ul class="footer-social-list">
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="28px" height="28px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-ideal')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="48px" height="39px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-Mastercard')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="56px" height="20px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-visa')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="40px" height="35px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-apple-pay')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="32px" height="32px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-thuiswinkel')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="32px" height="32px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-thuiswinkel_waarborg_Kleur_Verticaal')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="">
                            <svg class="footer-social-icon" width="28px" height="28px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-postnl')?>"></use>
                            </svg>
                        </a>
                    </li>
                    <li class="footer-social-list-item">
                        <a href="#" class="footer-social-list-item-link">
                            <svg class="footer-social-icon" width="28px" height="28px">
                                <use href="<?=$block->getViewFileUrl('images/icons.svg#icon-tweakers')?>"></use>
                            </svg>
                            <span class="section5__orange">Best</span>
                            webshop 2021
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
