<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Generic.Files.LineLength

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
?>
<tbody class="cart item">
<tr class="item-info">
    <td data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $block->escapeHtml($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo">
            <?php else: ?>
            <span class="product-item-photo">
            <?php endif; ?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </td>
    <?php endif; ?>
        <div class="product-item-details">
            <strong class="product-item-name">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $block->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
    <td class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
        <div class="field qty">
            <div class="item-actions">
                <div colspan="4">
                    <div class="actions-toolbar">
                        <?= /* @noEscape */ $block->getActions($_item) ?>
                    </div>
                </div>
            </div>
            <div class="control qty">
                <div class="btn-qty-minus">-</div>
                <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                    <!-- <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span> -->
                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           type="number"
                           size="4"
                           step="any"
                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                           class="input-text qty qty-controll-class"
                           data-validate="{required:true,'validate-greater-than-zero':true}"
                           data-item-qty="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                           data-role="cart-item-qty"/>
                </label>
                <div class="btn-qty-plus">+</div>
            </div>
        </div>
    </td>

    <?php if ($_options = $block->getOptionList()): ?>
        <dl class="item-options">
            <?php foreach ($_options as $_option): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['span', 'a']) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                    <?php endif; ?>
                </dd>
            <?php endforeach; ?>
        </dl>
    <?php endif; ?>
            <div class="special-p">
                <h4>Included for free</h4>
                <a href="">1-year Norton 360 antivirus</a><span class="special-p-container-grey"> worth 69,99</span>
                <h4>Choose your insurance</h4>
                <div class="special-p-container">
                    <input type="radio" name="backup">
                    <label >No, I'll pay myself if repair or replacement isn't covered under warranty.</label>
                </div>
                <div class="special-p-container">
                    <input type="radio" name="backup">
                    <label>
                        <div class="special-p-container-text">2-year Backup Plan Damage</div>
                        <div class="special-p-container-grey">39,90 one-time payment</div>
                    </label>
                </div>
                <div class="special-p-container">
                    <input type="radio" name="backup">
                    <label >
                        <div class="special-p-container-text">2-year Backup Plan Complete</div>
                        <div class="special-p-container-grey">79,90 one-time payment</div>
                    </label>
                </div>
                <div class="special-p-container">
                    <input type="radio" name="backup">
                    <label >
                        <div class="special-p-container-text">3-year Backup Plan Damage</div>
                        <div class="special-p-container-grey">69,90 one-time payment</div>
                    </label>
                </div>
                <div class="special-p-container">
                    <input type="radio" name="backup">
                    <label >
                        <div class="special-p-container-text">3-year Backup Plan Complete</div>
                        <div class="special-p-container-grey">119,90 one-time payment</div>
                    </label>
                </div>
            </div>
    <?php if ($messages = $block->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
            <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                <div><?= $block->escapeHtml($message['text']) ?></div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
    <?php if ($addInfoBlock): ?>
        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
    <?php endif; ?>
    </div>
    </td>



    <td class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
        <?php if ($canApplyMsrp): ?>
            <span class="cart msrp subtotal">--</span>
        <?php else: ?>
            <?= $block->getRowTotalHtml($_item) ?>
        <?php endif; ?>
    </td>
</tr>
</tbody>
<script type="text/x-magento-init">
    {
        "*": {
            "qtyControl":{}
        }
    }
</script>
