<div class="widget-category">
    <h3 class="widget-category-header">Laptops</h3>
    <div class="widget-category-list">
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-laptops.png')?>" alt="">
            <div>Laptops</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-gaming.png')?>" alt="">
            <div>Gaming laptops</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-chromebook.png')?>" alt="">
            <div>Chromebook models</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-business.png')?>" alt="">
            <div>Business laptop</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-apple.png')?>" alt="">
            <div>Apple MacBook</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-advice.png')?>" alt="">
            <div>Advice on laptops</div>
        </a>
    </div>
    <h3 class="widget-category-header">Desktops</h3>
    <div class="widget-category-list">
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-desktops.png')?>" alt="">
            <div>Desktops</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-gamingpc.png')?>" alt="">
            <div>Gaming PCs</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-allinonepc.png')?>" alt="">
            <div>All-in-one PCs</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-businesspc.png')?>" alt="">
            <div>Business PCs</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-applepc.png')?>" alt="">
            <div>Apple Mac</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-advicepc.png')?>" alt="">
            <div>Advice on desktops</div>
        </a>
    </div>
    <h3 class="widget-category-header">Monitors</h3>
    <div class="widget-category-list">
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-monitors.png')?>" alt="">
            <div>Monitors</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-gamingmonitors.png')?>" alt="">
            <div>Gaming monitors</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-ultrawidemonitors.png')?>" alt="">
            <div>Ultrawide monitors</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-businessmonitors.png')?>" alt="">
            <div>Business monitors</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-bundlemonitors.png')?>" alt="">
            <div>Monitor bundles</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-advicemonitors.png')?>" alt="">
            <div>Advice on monitors</div>
        </a>
    </div>
    <h3 class="widget-category-header">Popular accessories</h3>
    <div class="widget-category-list">
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-mouse.png')?>" alt="">
            <div>Mouses</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-software.png')?>" alt="">
            <div>Office software</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-covers.png')?>" alt="">
            <div>Laptop covers</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-keyboards.png')?>" alt="">
            <div>Keyboards</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-sets.png')?>" alt="">
            <div>Keyboard and mouse sets</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-stations.png')?>" alt="">
            <div>Docking stations</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-acer.png')?>" alt="">
            <div>Acer</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-apple.png')?>" alt="">
            <div>Apple</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/asus.png')?>" alt="">
            <div>Asus</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-hp.png')?>" alt="">
            <div>HP</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/lenovo.png')?>" alt="">
            <div>Lenovo</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-microsoft.png')?>" alt="">
            <div>Microsoft</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-aoc.png')?>" alt="">
            <div>AOC</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-lg.png')?>" alt="">
            <div>LG</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-philips.png')?>" alt="">
            <div>Philips</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-samsung.png')?>" alt="">
            <div>Samsung</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-logitech.png')?>" alt="">
            <div>Logitech</div>
        </a>
        <a href="#" class="widget-category-list-item">
            <img src="<?=$block->getViewFileUrl('Max_LaptopsPageWidget::images/widget-trust.png')?>" alt="">
            <div>Trust</div>
        </a>

    </div>
</div>
