<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart"
                    id="product-addtocart-button" disabled>
                <span>
                    <svg class="icon icon--height-4" aria-hidden="true" viewBox="0 0 59.2 40.1" focusable="false">

                <path d="M42.8,17.6H30c-1.7,0-3-1.3-3-3s1.3-3,3-3h12.8c1.7,0,3,1.3,3,3S44.5,17.6,42.8,17.6z"></path>
                <circle cx="23.7" cy="36.1" r="4"></circle>
                <circle cx="49.1" cy="36.1" r="4"></circle>
                <path d="M57,5.1c-1.6-0.4-3.2,0.5-3.7,2.1l-4.1,15.3H23.6L18.2,2.2C17.8,0.9,16.7,0,15.3,0H3.1c-1.7,0-3,1.3-3,3s1.3,3,3,3h7.6c1.4,0,2.5,0.9,2.9,2.2l0,0l4.8,18.1c0.4,1.3,1.5,2.2,2.9,2.2h30.2c1.4,0,2.5-0.9,2.9-2.2l4.7-17.5C59.5,7.1,58.6,5.5,57,5.1z"></path>

            </svg>
                    In my shopping cart
                </span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
